title: Hi, I am Brian!
logo: assets/headshot_roundsquare.png
description: Welcome to my portfolio site!
show_downloads: false
github:
  is_project_page: false
plugins:
- jekyll-remote-theme 
remote_theme: pages-themes/hacker@v0.2.0
